### ISSUE TITLE
Inspecting shows no items

### ISSUE THREAD

**Issue by rebz** [taxidriveer/Examiner#6]
As of today, when I go to inspect someone I will see no items. If I inspect myself it works fine.

Sometimes when I go from inspecting myself to inspecting another it will briefly show their items, then hide said items while showing empty slots, then the slots will disappear.

**Inspecting someone else**
![image](https://user-images.githubusercontent.com/628385/69669524-0b41fc00-1060-11ea-8ebc-56f97f22f8fc.png)

**Inspecting myself**
![image](https://user-images.githubusercontent.com/628385/69669567-1bf27200-1060-11ea-8f1e-aa7f28e5a435.png)

**Comment by taxidriveer** [comment]
Hi Rebz,

For some reason I don't have this problem, could you let me know how many player entry do you have in the cache ? I'm wondering if you can have this behavior if it gets too big...

PS: You can clear the cache by doing a right click on "Cache" ->"Delete All Entries" and make sure to reload the UI.

**Comment by rebz** [comment]
@taxidriveer - I had 510 cached players. I cleared cache and performed a `/reload`. However, the issue persists.

![image](https://user-images.githubusercontent.com/628385/69769626-951ec180-1153-11ea-8d1c-15a5eb5dd20e.png)

**Comment by rebz** [comment]
I relaunched the game and the issue persists.

**Comment by rebz** [comment]
If I select someone, click `More > Configurations` and toggle the `Smart Tooltip Anchor` on/off, it will enable/disable the `Stats` button. Then I close the inspect window, re-open, and I can view the person's gear. However, if I close and re-open their gear is hidden; rinse and repeat.

**Comment by rebz** [comment]
I've tried clearing my cache files and re-installing from scratch, still can't get the addon to work properly as it should.

**Comment by wazerstar** [comment]
@taxidriveer & @rebz 


I had the same issue, and I just figured out. Its [honorspy](https://www.curseforge.com/wow/addons/honorspy) addon causing this issue, i deleted over 120 addons to figure out what was causing this issue with examiner not working.

**Comment by rebz** [comment]
@wazerstar interesting. I will have to try this out later today. Worth noting that I too am using Honorspy.

**Comment by wazerstar** [comment]
> 
> 
> @wazerstar interesting. I will have to try this out later today. Worth noting that I too am using Honorspy.

What can I say, unless another addon + honorspy at the same time triggering examiner not work, could possible be, since i still had some left after checking all those addon, but maybe original poster should check out if honorspy is causing that for him too.

**Comment by vanillalad** [comment]
can confirm, it is honorspy causing this isssue.

**Comment by rebz** [comment]
Confirmed, it is Honorspy. Disabled the addon and Examiner worked immediately.

Closing this issue.

**Comment by taxidriveer** [comment]
Thanks all, I'll investigate if I can fix this problem.

**Comment by taxidriveer** [comment]
Thanks all, after a quick investigation I think this is due to HonorSpy calling "ClearInspectPlayer" and "NotifyInspect" multiple times when you mouseover a player. 

In honorspy.lua at line 58 you have the following code
> if (name ~= inspectedPlayerName) then -- changed target, clear currently inspected player
>  	**ClearInspectPlayer();**
>  	...
> end

at line 79:
> -- we gonna inspect new player, clear old one
> **ClearInspectPlayer();**
> ...
> **NotifyInspect(unitID);**

at line 103

> **ClearInspectPlayer();**
> **NotifyInspect("target")**; -- change real target back to player's target, broken by prev NotifyInspect call

"NotifyInspect" will request inventory data from the player, and since we move our mouse a lot this is beeing called multiples times and confuse Examiner. 
"ClearInspectPlayer" seems to stop the WoW client from gathering inventory data from the unit. Sometimes Examiner won't have the time to cache the items and will display blank items..
(see [WoWWiki](https://wowwiki.fandom.com/wiki/API_NotifyInspect))

A quick way to make Examiner working with HonorSpy is to:
1. Target a player
2. Make sure you are not targeting someone with your cursor for the next 4 seconds (important!)
3. Inspect the unit with a keybind 
(You can configure a keybind in the WoW menu -> Key Bindings -> Other)

You will notice that Examiner will be able to show the player items.
Unfortunately I'm not sure that I will be able to fix this, I suggest to either use HonorSpy or Examiner.

**Comment by wazerstar** [comment]
Thanks for providing that info, so nothing we can do for honorspy dev to make another way that works better? Else I will just mark my target hold down mouse2(mouse disapear & wait 4 seconds and press my newly bind hotkey I for inspect :P )

**Comment by vanillalad** [comment]
Just use Honor Grinding Tracker instead of honorspy, works basically the same but doesn't break when you use it together with Examiner.

**Comment by wazerstar** [comment]
> 
> 
> Just use Honor Grinding Tracker instead of honorspy, works basically the same but doesn't break when you use it together with Examiner.

I Do not like  honortracker, and does only track from the session you are in and had enabled the addon. So inspect on I for me while not pointing cursor at any for 4 seconds works fine for me atm.
